### PR TITLE
Driver updates and new demo app (RatSLAM).

### PR DESCRIPTION
**Pull request by sem23**
Hey Takashi!

I finished next update for cozmo driver! This update includes a keyboard teleop node and a demo application using RatSLAM. Feel free to test before merge! Note: As I merged back your master branch to my one, it seems that the initial merge is now also listed here. But this should be ok!

Best Regards,
Peter

### CODE REVIEW

**Comment by OTL** [comment]
Hi,
it seems super great!
I'll check it this week end before merging.

**Comment by OTL** [comment]
How about adding [imu_tools](http://wiki.ros.org/rviz_imu_plugin) to use your rviz config?

```
$ sudo apt-get install ros-kinic-imu-tools (for kinetic)
```

Add it to <run_dependency> ?

**Comment by OTL** [comment]
Any way, I merge this PR. Thanks.
I want to try ratslam someday, please help in the ratslam issue.

**Comment by sem23** [comment]
Hi, 
Sorry for the late reply! Were you able to get the ratslam demo working?
Cheers, 
Peter

**Pull request merged**
